# Generated by Django 2.0 on 2018-09-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('q1', models.IntegerField(default=99)),
                ('q2', models.IntegerField(default=99)),
                ('q3', models.IntegerField(default=99)),
                ('q4', models.IntegerField(default=99)),
                ('q5', models.IntegerField(default=99)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
